### ISSUE TITLE
unsubscribe()

### ISSUE THREAD

**Issue by kerolloz** [github/check-all#13]
what does the unsubscribe function do?
should the check-all functionality stop when it's called?
I mean when I click check all button it shouldn't work when I unsubscribe!

**Comment by muan** [comment]
> should the check-all functionality stop when it's called?

Yes. You can find some description for the Subscription interface in https://github.com/josh/selector-observer/pull/8.

https://github.com/github/check-all/blob/4b108b685f8938112cc82e28ca02de13f9ed0495/check-all.js#L112-L115
