### ISSUE TITLE
Shift click with custom checkboxes

### ISSUE THREAD

**Issue by rbague** [github/check-all#16]
I just set up this library with bootstrap [custom checkboxes](https://getbootstrap.com/docs/4.4/components/forms/#checkboxes-and-radios-1), and everything works fine except the `shift click` functionality.
After investigating this is probably because [onMouseDown](https://github.com/github/check-all/blob/v0.3.0/check-all.js#L62) checks that the event target has the `data-check-all-item` attribute, which is not the case as bootstrap hides the input and displays the checkbox in the label's `:before` and `:after` pseude-elements, causing the `event.target` to be the label, which does not have the attribute.

It might happen the same with other CSS libraries that use a similiar approach to change the checkbox design like [Semantic UI](https://semantic-ui.com/modules/checkbox.html) or [iCheck](http://icheck.fronteed.com/).

I don't know if there is an easy fix or of it is worth it, but in that case it might be required to explain it in the README.

Here is a simple example so you can see the behaviour I'm describing: https://codesandbox.io/s/githubcheck-all-bootstrap-custom-checkboxes-76jv5

**Comment by muan** [comment]
Thanks for the report. With 0.4.0 this should be fixed. See #18 for the issues around text selection & firefox though.

![](https://cl.ly/0583f66d2617/Screen%20Recording%202020-05-27%20at%2017.15.gif)

**Comment by rbague** [comment]
Awesome, thanks!
