### ISSUE TITLE
the URL in about gives 404

### ISSUE THREAD

**Issue by kerolloz** [github/check-all#19]
http://github.github.io/check-all/examples
![image](https://user-images.githubusercontent.com/36763164/94941075-aef80600-04d4-11eb-880f-2d2931410b5f.png)

**Comment by muan** [comment]
Fixed https://github.github.io/check-all/examples/?fixed. Thanks for reporting this.

cc @keithamus @koddsson this seems to be caused by the branch name change and so gh-pages stopped building. Might be good to audit other repos.
